services:
  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./beszel_agent_data:/var/lib/beszel-agent
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    environment:
      LISTEN: 45876
      KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFbMj/W6oT9440QejCiVlJbnuBlWK/mCxJnzEHO1dOYq"
      TOKEN: ${BESZEL_AGENT_TOKEN}
      HUB_URL: https://beszel.yral.com
    security_opt:
      - apparmor:unconfined

  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    hostname: clickhouse-replica-1
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml:ro
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml:ro
      - ./clickhouse/storage_config.xml:/etc/clickhouse-server/config.d/storage_config.xml:ro
      - ./clickhouse/data:/var/lib/clickhouse
      - ./clickhouse/logs:/var/log/clickhouse-server
    environment:
      AWS_ACCESS_KEY_ID: Y8C0A8G3J7ZZXPN6XJWJ
      AWS_SECRET_ACCESS_KEY: ${CLICKHOUSE_S3_STORAGE_SECRET_ACCESS_KEY}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
