all:
  hosts:
    clickhouse-keeper-1:
      ansible_host: 88.99.97.49
    clickhouse-keeper-2:
      ansible_host: 138.201.137.181
    clickhouse-keeper-3:
      ansible_host: 136.243.150.84
    clickhouse-replica-1:
      ansible_host: 94.130.13.115
    clickhouse-replica-2:
      ansible_host: 88.99.151.102
