all:
  hosts:
    clickhouse-keeper-1:
      ansible_host: 88.99.97.49
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    clickhouse-keeper-2:
      ansible_host: 138.201.137.181
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    clickhouse-keeper-3:
      ansible_host: 136.243.150.84
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    clickhouse-replica-1:
      ansible_host: 94.130.13.115
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    clickhouse-replica-2:
      ansible_host: 88.99.151.102
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
